begin;
do $restore$ declare org uuid:='0d1ee589-5acc-4321-a560-b6f176394a6e'; sid uuid; begin
if not exists(select 1 from crm.outreach_sequences where organization_id=org and settings->>'library_key'='cafeworking-parceiros-indicacao') then
insert into crm.outreach_sequences(organization_id,nome,objetivo,status,settings) values(org,'CafeWorking — indicação de endereço fiscal','Conversar com escritórios que podem indicar clientes para endereço fiscal','DRAFT','{"publico": "prospect", "library_key": "cafeworking-parceiros-indicacao", "service": "Indicação de endereço fiscal"}'::jsonb) returning id into sid;
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,0,'EMAIL',0,'{"subject": "Parceria para endereço fiscal | CafeWorking", "body": "Olá, {{name}}!\n\nSou o assistente comercial do CafeWorking, empresa do Grupo Ciatos. Estamos conversando com contadores e escritórios que atendem empresas com necessidade de endereço fiscal.\n\nEssa demanda aparece entre os clientes da {{company}}? Se fizer sentido, posso encaminhar uma conversa com nossa equipe para avaliar uma parceria de indicação.\n\nEquipe CafeWorking"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,1,'EMAIL',4320,'{"subject": "Como vocês atendem demandas de endereço fiscal?", "body": "Olá, {{name}}!\n\nRetomando meu contato: quando um cliente da {{company}} precisa de endereço fiscal, vocês já têm um parceiro para encaminhar essa necessidade?\n\nNo CafeWorking, queremos entender esse fluxo e conversar sobre uma possível parceria. A disponibilidade e a adequação para cada atividade precisam ser avaliadas pela equipe.\n\nFaz sentido conversarmos?\n\nEquipe CafeWorking"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,2,'EMAIL',5760,'{"subject": "Podemos alinhar uma parceria com a {{company}}?", "body": "Olá, {{name}}!\n\nPodemos organizar uma conversa breve sobre como receber indicações de clientes da {{company}} interessados em endereço fiscal, quais informações seriam necessárias e como acompanhar cada encaminhamento.\n\nCondições comerciais e responsabilidades seriam combinadas com você antes de qualquer compromisso. Você cuida dessas parcerias ou há outra pessoa indicada?\n\nEquipe CafeWorking"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,3,'EMAIL',7200,'{"subject": "Encerrando meu contato sobre a parceria", "body": "Olá, {{name}}!\n\nEste é meu último contato desta sequência sobre uma possível parceria com o CafeWorking para endereço fiscal.\n\nSe for uma oportunidade para a {{company}}, basta responder e encaminho seu interesse à nossa equipe. Se não for o momento, encerro por aqui.\n\nObrigado pela atenção.\n\nEquipe CafeWorking"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,4,'WAIT',7200,'{}');
end if;
end $restore$;
commit;