begin;
do $campaign$ declare org uuid:='0d1ee589-5acc-4321-a560-b6f176394a6e'; sid uuid:='0de5f284-e8db-4a42-85b2-27cb7a9f4048'; begin
perform 1 from crm.outreach_sequences where id=sid and organization_id=org and status='DRAFT' for update;
if not found then raise exception 'Cadência não está em rascunho'; end if;
if exists(select 1 from crm.sequence_enrollments where sequence_id=sid) then raise exception 'Cadência já possui inscrições'; end if;
update crm.outreach_sequences set nome='CafeWorking — rede nacional de parceiros',objetivo='Qualificar contabilidades, advogados e consultorias com espaço disponível para oferecer endereço fiscal e aluguel de salas pela marca e plataforma CafeWorking',settings=settings || '{"service": "Parceria CafeWorking: endereço fiscal e aluguel de salas", "audience": "Contabilidades, escritórios de advocacia e consultorias de todo o Brasil", "copy_version": "2026-09-29-rede-parceiros", "commercial_terms": "Adesão sem custo; repasse de 75% ou 85% conforme condições da parceria; pagamento e divisão via Asaas"}'::jsonb,stop_on_reply=true,stop_on_meeting=true,updated_at=now() where id=sid;
delete from crm.outreach_steps where sequence_id=sid;
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,0,'EMAIL',0,'{"subject": "Seu escritório pode gerar renda além da sua atividade principal?", "body": "Olá, {{name}}!\n\nUma sala que fica vazia parte do dia ou uma estrutura maior do que sua equipe precisa pode abrir uma nova frente de receita para a {{company}}.\n\nO CafeWorking está formando uma rede de parceiros em todo o Brasil: contabilidades, escritórios de advocacia e consultorias que desejam oferecer endereço fiscal e aluguel de salas usando nossa marca, site e aplicativo.\n\nA adesão é sem custo. O parceiro recebe 75% ou 85% do valor cobrado pelo serviço, conforme as condições da parceria.\n\nA {{company}} tem um espaço que poderia aproveitar melhor? Responda com sua cidade e o tipo de espaço disponível, e nossa equipe conversa com você.\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,1,'EMAIL',4320,'{"subject": "Foi de uma sede ociosa que nasceu essa ideia", "body": "Olá, {{name}}!\n\nO Diego, fundador do CafeWorking, passou por uma situação que muitos empresários conhecem: comprou um imóvel e ficou com parte da sede ociosa. A decisão foi transformar esse espaço em coworking.\n\nEssa experiência inspirou uma proposta: ajudar outros empresários a aproveitar melhor a estrutura que já têm.\n\nSe a {{company}} tem uma sala pouco usada ou um imóvel com capacidade disponível, vale avaliar se ele pode gerar renda extra com endereço fiscal ou locação de salas. Cada espaço e atividade precisam ser avaliados antes da oferta.\n\nVocê também tem alguma área que hoje fica mais tempo vazia do que ocupada?\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,2,'EMAIL',5760,'{"subject": "75% ou 85% para o parceiro: como funciona", "body": "Olá, {{name}}!\n\nQuero deixar claro o modelo de parceria do CafeWorking:\n\n• Adesão sem custo.\n• Oferta de endereço fiscal e aluguel de salas com a marca CafeWorking, pelo nosso site e aplicativo.\n• Repasse ao parceiro de 75% ou 85% do valor cobrado pelo serviço, conforme as condições da parceria.\n• O cliente paga pela plataforma, e a divisão dos valores entre as partes é feita pelo Asaas.\n\nAntes de aderir, nossa equipe apresenta qual percentual se aplica ao seu caso e esclarece as condições, os prazos e as responsabilidades. A receita depende das contratações; não há promessa de ocupação ou ganho garantido.\n\nQuer entender qual formato faz sentido para a {{company}}? Basta responder “quero conhecer”.\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,3,'EMAIL',5760,'{"subject": "Você já tem o espaço. Vale avaliar uma nova fonte de receita?", "body": "Olá, {{name}}!\n\nContabilidades, escritórios de advocacia e consultorias costumam ter uma estrutura pensada para atender bem: endereço, recepção e salas. Parte dessa estrutura pode ficar disponível em determinados horários.\n\nA proposta do CafeWorking é avaliar como aproveitar essa capacidade para oferecer endereço fiscal e aluguel de salas a outros clientes, usando nossa plataforma e nossa marca.\n\nNão é necessário decidir agora. O primeiro passo é entender o que você tem disponível e se o modelo combina com a operação da {{company}}.\n\nHoje faria mais sentido avaliar endereço fiscal, aluguel de salas ou os dois?\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,4,'EMAIL',5760,'{"subject": "Três informações para avaliar sua parceria com o CafeWorking", "body": "Olá, {{name}}!\n\nSe a ideia de gerar renda extra com seu espaço chamou sua atenção, podemos começar por três informações:\n\n1. Em qual cidade e estado fica o imóvel?\n2. Você tem sala disponível, estrutura para endereço fiscal ou ambos?\n3. Você é a pessoa responsável por avaliar essa parceria?\n\nCom isso, nossa equipe pode conversar sobre a adequação do espaço, as condições de participação e o repasse de 75% ou 85%, conforme o modelo aplicável.\n\nA adesão é sem custo. Não precisa preparar uma apresentação: pode responder com essas informações aqui mesmo.\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,5,'EMAIL',7200,'{"subject": "Deixo a porta aberta para a {{company}}", "body": "Olá, {{name}}!\n\nEste é meu último contato desta sequência.\n\nA proposta do CafeWorking é transformar capacidade ociosa em uma oportunidade de receita: parceiros em todo o Brasil oferecendo endereço fiscal e aluguel de salas com nossa marca, site e aplicativo.\n\nSe fizer sentido avaliar o espaço da {{company}}, responda “vamos conversar”. Encaminho seu interesse à nossa equipe para apresentar a parceria, sem custo de adesão e sem compromisso de contratação nesta conversa.\n\nSe não for o momento, encerro por aqui. Obrigado pela atenção.\n\nEquipe CafeWorking | Grupo Ciatos"}'::jsonb);
insert into crm.outreach_steps(sequence_id,ordem,tipo,delay_minutes,config) values(sid,6,'WAIT',7200,'{}');
update crm.organizations set settings=settings || '{"commercial_focus":"Rede nacional de parceiros para endereço fiscal e aluguel de salas, com marca, site e app CafeWorking","target_audience":"Contabilidades, escritórios de advocacia e consultorias com espaço disponível em todo o Brasil"}'::jsonb,updated_at=now() where id=org;
insert into crm.platform_audit(action,entity_id,details) values('cadence_copy_updated',org,'{"source":"explicit_user_request","campaign":"CafeWorking — rede nacional de parceiros","emails":6,"status":"DRAFT"}');
end $campaign$;
commit;