/** Generate an idempotent CRM-only SQL seed: npx tsx supabase/ops/install-sales-playbooks.ts > playbooks.sql */
type Offer = { key: string; name: string; question: string; diagnosis: string[]; value: string; caution: string; objection: string; reply: string; next: string };

const offers: Offer[] = [
  { key: 'contabilidade', name: 'Contabilidade', question: 'Como vocês acompanham hoje obrigações, prazos e informações contábeis para decidir?', diagnosis: ['Qual parte da rotina contábil mais toma tempo da equipe?', 'Com que frequência você recebe informações úteis para tomar decisões?', 'O que faria uma troca de contador valer a pena?'], value: 'Podemos avaliar a rotina atual e desenhar uma transição contábil com escopo, responsáveis e prazos claros.', caution: 'A transição depende da documentação e da situação cadastral; só assumimos prazos após análise.', objection: 'Já tenho contador.', reply: 'Ótimo. Não proponho trocar por trocar. Se hoje tudo funciona bem, faz sentido manter. Há alguma informação ou prazo que você gostaria de melhorar?', next: 'Uma conversa de 20 minutos sobre a rotina e, se houver oportunidade, um diagnóstico de transição.' },
  { key: 'juridico', name: 'Jurídico empresarial', question: 'Quem apoia a empresa quando surgem contratos, decisões societárias ou dúvidas jurídicas?', diagnosis: ['Que tipo de demanda jurídica aparece com mais frequência?', 'Como vocês revisam contratos antes de assinar?', 'Em qual decisão seria útil ter uma avaliação preventiva?'], value: 'A equipe jurídica pode organizar as demandas e avaliar prioridades, riscos e alternativas dentro de um escopo definido.', caution: 'Nenhum resultado jurídico é garantido; a orientação depende dos fatos e documentos.', objection: 'Só procuro advogado quando tenho um problema.', reply: 'Entendo. Muitas empresas funcionam assim. Um olhar preventivo pode ajudar nas decisões antes de assumir compromissos. Há algum contrato ou decisão que já mereça revisão?', next: 'Uma triagem com o profissional responsável para delimitar a demanda e a proposta.' },
  { key: 'crise', name: 'Planejamento de crise', question: 'Se os próximos meses exigirem escolhas difíceis, quais prioridades a gestão precisa proteger?', diagnosis: ['Quais decisões não podem esperar?', 'Que indicadores vocês acompanham para antecipar pressão de caixa ou operação?', 'Quem participa da definição de prioridades?'], value: 'Podemos estruturar um diagnóstico de cenário, prioridades e alternativas para apoiar decisões da gestão.', caution: 'Não presumimos crise nem prometemos recuperação; recomendações dependem de dados e análise.', objection: 'Nossa empresa não está em crise.', reply: 'Melhor ainda. Planejar alternativas enquanto há espaço de manobra ajuda a decidir com calma. Existe alguma incerteza que valha mapear?', next: 'Uma conversa estratégica para entender cenário, metas e dados disponíveis.' },
  { key: 'tributario', name: 'Planejamento tributário', question: 'Quando foi a última revisão técnica do enquadramento e das rotinas tributárias da empresa?', diagnosis: ['Qual regime tributário e atividade principal vocês têm hoje?', 'Houve mudança de receita, operação ou estrutura desde a última revisão?', 'Que documentação está disponível para uma avaliação técnica?'], value: 'A equipe pode revisar cenários legais e documentados e apresentar alternativas compatíveis com a operação.', caution: 'Não prometemos economia nem mudança de regime antes de uma análise técnica; qualquer decisão exige validação.', objection: 'Meu contador já cuida dos tributos.', reply: 'Perfeito. A revisão pode complementar o trabalho contábil e testar se as premissas continuam atuais, com o contador envolvido quando fizer sentido.', next: 'Uma reunião de escopo para definir documentos, período e critérios da avaliação.' },
  { key: 'holding', name: 'Holding e planejamento patrimonial', question: 'Os sócios já conversaram sobre organização patrimonial e sucessão?', diagnosis: ['Qual é o objetivo principal: governança, sucessão ou organização dos bens?', 'Quem precisa participar da decisão?', 'Existe alguma restrição jurídica, familiar ou fiscal já conhecida?'], value: 'Podemos avaliar alternativas de organização patrimonial e sucessória; uma holding é apenas uma possibilidade.', caution: 'Estrutura, custos e efeitos tributários dependem de análise jurídica e fiscal individual.', objection: 'Holding parece cara e complexa.', reply: 'Pode ser, e talvez nem seja adequada ao seu caso. Primeiro comparamos objetivo, custos e alternativas; só recomendamos uma estrutura se houver fundamento.', next: 'Uma conversa reservada com os responsáveis pelo planejamento patrimonial.' },
  { key: 'credito', name: 'Recuperação de crédito tributário', question: 'Já houve uma revisão documentada de possíveis créditos tributários?', diagnosis: ['Quais tributos e períodos foram revisados?', 'A empresa tem os documentos fiscais e contábeis desse período?', 'Como são aprovadas oportunidades que dependem de interpretação tributária?'], value: 'Nossa equipe pode verificar documentação e viabilidade de uma revisão técnica de créditos.', caution: 'A existência de crédito, o valor e a possibilidade de aproveitamento não são garantidos.', objection: 'Parece arriscado.', reply: 'A cautela é correta. Por isso começamos por escopo, documentos, fundamento e riscos; não orientamos aproveitamento sem validação técnica.', next: 'Uma triagem documental para dizer se faz sentido aprofundar a análise.' },
  { key: 'bank', name: 'Ciatos Bank', question: 'Qual necessidade financeira da operação você gostaria de resolver primeiro?', diagnosis: ['O desafio envolve pagamentos, recebimentos, crédito ou gestão financeira?', 'Qual processo atual gera mais trabalho?', 'Quais custos, prazos e critérios são decisivos para avaliar uma solução?'], value: 'Podemos apresentar as soluções disponíveis e verificar aderência às necessidades da empresa.', caution: 'Produtos, taxas, disponibilidade e eventual aprovação dependem das condições vigentes e de análise.', objection: 'Já uso outro banco.', reply: 'Faz sentido. Não há motivo para mudar sem ganho claro. Qual aspecto do serviço atual você gostaria de comparar?', next: 'Uma apresentação objetiva da solução pertinente, com condições confirmadas pela equipe.' },
  { key: 'racionaliza', name: 'Racionaliza', question: 'Qual processo ou custo da empresa mais precisa de uma avaliação agora?', diagnosis: ['Qual é a prioridade de melhoria neste trimestre?', 'Como vocês medem o resultado desse processo hoje?', 'Quem participa da decisão de contratar uma solução nova?'], value: 'Podemos entender a necessidade e apresentar os serviços da Racionaliza que sejam pertinentes.', caution: 'Escopo, preço e resultados devem ser confirmados com a equipe responsável.', objection: 'Ainda não conheço a Racionaliza.', reply: 'Sem problema. Em vez de uma apresentação genérica, diga qual prioridade você tem e mostramos apenas o que se relaciona a ela.', next: 'Uma conversa curta com a equipe da Racionaliza para qualificar a demanda.' },
  { key: 'log', name: 'CiatosLog', question: 'Onde a operação logística exige mais atenção hoje?', diagnosis: ['Qual etapa da logística gera atrasos ou retrabalho?', 'Quais regiões, volumes e frequência precisam ser atendidos?', 'Que indicadores você usaria para comparar uma alternativa?'], value: 'Podemos avaliar a demanda e apresentar uma proposta logística com escopo e condições definidos.', caution: 'Cobertura, capacidade, prazo e preço dependem da rota e da confirmação operacional.', objection: 'Já tenho transportadora.', reply: 'Ótimo. Talvez exista uma rota ou demanda complementar que valha comparar. Onde você sente mais necessidade de alternativa?', next: 'Uma avaliação de rota, volume e frequência pela equipe operacional.' },
  { key: 'cafeworking', name: 'CafeWorking · coworking e salas', question: 'Como vocês resolvem hoje a necessidade de salas, reuniões e endereço comercial?', diagnosis: ['A demanda é recorrente ou pontual?', 'Qual cidade, frequência e formato de espaço são necessários?', 'O que pesa mais: localização, flexibilidade ou infraestrutura?'], value: 'Podemos apresentar espaços e serviços disponíveis conforme local, necessidade e disponibilidade.', caution: 'Endereço, vagas, disponibilidade e condições precisam ser confirmados antes da contratação.', objection: 'Trabalho bem de casa.', reply: 'Faz sentido. O espaço só acrescenta valor quando existe uma necessidade concreta, como receber um cliente ou usar sala por algumas horas. Isso acontece na sua rotina?', next: 'Uma apresentação de opções e valores atuais para a cidade e o uso desejados.' },
  { key: 'cafeworking-parcerias', name: 'CafeWorking · parceria de endereço fiscal', question: 'Seu escritório tem uma sala ou imóvel com capacidade ociosa que poderia gerar receita adicional?', diagnosis: ['Em qual cidade fica o espaço e que estrutura ele oferece?', 'Quantas salas ou horários ficam ociosos?', 'Você atenderia clientes de endereço fiscal, locação de salas ou ambos?', 'Quem aprova uma parceria e as condições comerciais?'], value: 'O CafeWorking oferece plataforma, aplicativo e marca para parceiros divulgarem endereço fiscal e salas, com adesão sem custo conforme as regras vigentes. A operação de pagamento e repasse usa a plataforma e o Asaas.', caution: 'A participação anunciada de 75% ou 85% depende da modalidade e do contrato; confirme critérios, custos, responsabilidades e disponibilidade antes de prometer valores ou renda.', objection: 'Não quero investir nem depender de mais uma operação.', reply: 'É uma preocupação justa. Eu transformei uma sede ociosa em coworking justamente para aproveitar melhor um imóvel já existente. Podemos mostrar o fluxo de cadastro, atendimento e repasse, e você decide se a rotina cabe na sua estrutura.', next: 'Uma demonstração da plataforma e uma avaliação do imóvel, cidade, modalidade e minuta de parceria.' },
];

const orgOffers: Record<string, string[]> = {
  '00000000-0000-4000-8000-000000000001': offers.map(o => o.key),
  '8345da0f-171a-44c4-ab3b-b5b468487c09': ['tributario', 'credito'],
  '97dbf5e9-9ea2-4fb1-9de9-7561a1810567': ['racionaliza'],
  'd136ff75-88e2-49f0-a57c-34f8ffde2468': ['holding'],
  '86086314-ad9c-4064-832d-21a0ce9fc4a7': ['log'],
  '5080f093-3019-4015-b048-3d837aae21ee': ['contabilidade'],
  '791a8796-503a-4817-b516-f229f54b58af': ['crise', 'tributario', 'credito'],
  'eb2c1641-b38c-4104-b097-f74398c50f54': ['juridico'],
  '0934f7bb-ceee-4fc1-95fa-92d1267a1d9c': ['bank'],
  '0d1ee589-5acc-4321-a560-b6f176394a6e': ['cafeworking', 'cafeworking-parcerias'],
};

function scripts(offer: Offer) {
  const intro = `Olá, {{nome}}. Sou da equipe do Grupo Ciatos. ${offer.question}\n\nSe não for prioridade, tudo bem. Se fizer sentido, posso fazer duas perguntas para entender antes de sugerir qualquer solução?\n\n[Se aceitar] O que motivou você a olhar para esse tema agora?\n[Se não for a pessoa certa] Quem costuma avaliar isso na {{empresa}}?\n[Se não houver interesse] Agradeça, registre a preferência e encerre.\n\n${offer.caution}`;
  const discovery = `Comece com contexto: “Quero entender a situação antes de sugerir algo.”\n\n${offer.diagnosis.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\nAprofunde: “O que acontece se nada mudar nos próximos meses?” e “Como vocês definiriam uma boa solução?”\n\nResuma sem exagerar: “Entendi que a prioridade é {{dor}}, com a decisão passando por {{decisor}}. Acertei?”\n\nSó depois apresente o caminho: ${offer.value}\n\n${offer.caution}`;
  const objections = `Objeção frequente: “${offer.objection}”\n\nResposta: “${offer.reply}”\n\nSe disser “Está caro”: “Faz sentido avaliar custo. Antes de comparar valores, podemos definir qual problema precisa ser resolvido e o escopo necessário? Uma proposta séria depende disso.”\n\nSe disser “Agora não”: “Entendo. O que precisaria mudar para esse assunto virar prioridade? Posso registrar sua preferência e retomar somente quando você pedir?”\n\nSe pedir garantia: “${offer.caution}”\n\nFeche sem pressionar: “Com esse contexto, vale uma conversa técnica ou prefere encerrar por aqui?”`;
  const close = `Retome o que ouviu: “Pelo que você contou, {{dor}} afeta {{impacto}} e a decisão envolve {{decisor}}. É isso?”\n\nProponha somente o próximo passo: ${offer.next}\n\n“Podemos reservar 20 minutos para isso? Qual horário funciona melhor e quem mais deveria participar?”\n\nAntes de agendar, confirme contato, autorização para retorno e o que será discutido. Registre no CRM as necessidades e as condições pendentes, sem dados sensíveis desnecessários.\n\nDepois da reunião, envie um resumo objetivo: necessidade, escopo em análise, responsável e data combinada.\n\n${offer.caution}`;
  return [
    { key: 'abertura', title: 'Abertura com permissão', objective: 'Primeiro contato', duration: 2, bullets: ['Pergunta específica do serviço', 'Pedir permissão para explorar', 'Respeitar recusa'], body: intro },
    { key: 'descoberta', title: 'Diagnóstico consultivo', objective: 'Descoberta', duration: 8, bullets: ['Entender a situação atual', 'Medir prioridade e impacto', 'Confirmar entendimento'], body: discovery },
    { key: 'objecoes', title: 'Objeções sem pressão', objective: 'Tratamento de objeções', duration: 5, bullets: ['Escutar e validar', 'Responder com contexto', 'Não prometer resultado'], body: objections },
    { key: 'proximo-passo', title: 'Convite para o próximo passo', objective: 'Agendamento', duration: 3, bullets: ['Resumir a necessidade', 'Convidar a pessoa certa', 'Registrar combinado'], body: close },
  ];
}

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`;
const now = new Date().toISOString();
let count = 0;
const sql = ['begin;'];
for (const [org, keys] of Object.entries(orgOffers)) for (const key of keys) {
  const offer = offers.find(item => item.key === key)!;
  for (const s of scripts(offer)) {
    const playbookKey = `ciatos-${key}-${s.key}-v1`;
    const id = crypto.randomUUID();
    const data = { id, playbookKey, title: `${offer.name} · ${s.title}`, objective: s.objective, serviceType: offer.name, funnelPhaseId: '', tone: 'consultivo', estimatedDuration: s.duration, bullets: s.bullets, tags: [offer.name, s.objective], isGlobal: true, authorId: '', versions: [{ id: 'v1', body: s.body, versionNumber: 1, createdAt: now, createdBy: 'Biblioteca Ciatos' }], currentVersionId: 'v1', usageStats: { totalUsed: 0, resolvedObjections: 0, convertedToMeeting: 0 } };
    sql.push(`insert into crm.scripts (id, organization_id, author_id, dados) select ${quote(id)}::uuid, ${quote(org)}::uuid, null, ${quote(JSON.stringify(data))}::jsonb where not exists (select 1 from crm.scripts where organization_id=${quote(org)}::uuid and dados->>'playbookKey'=${quote(playbookKey)});`);
    count++;
  }
}
sql.push('commit;');
process.stdout.write(sql.join('\n'));
console.error(`Generated ${count} scripts across ${Object.keys(orgOffers).length} companies.`);
