import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {cadenceLibrary} from '../lib/cadenceLibrary.ts';
import {renderMessage} from '../supabase/functions/_shared/outreach.ts';
import {cadenceHtml,chooseCandidate,companyDomain,validateReply,classifyReply,hotAlertText} from '../supabase/functions/_shared/sdr.ts';
import {graphPagePath,replyToken} from '../supabase/functions/_shared/sdrInbox.ts';
const org='00000000-0000-4000-8000-000000000001',user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
test('40 e-mails utilizáveis, sem variável pendente, descadastro e HTML escapado',()=>{
 assert.equal(cadenceLibrary.flatMap(c=>c.passos).length,40);
 for(const c of cadenceLibrary)for(const p of c.passos){const m=renderMessage({subject:p.assunto,body:p.corpo},{name:'Ana',company:'Alfa'},'https://example.test/unsubscribe');assert.ok(m.text.includes('unsubscribe'));assert.ok(m.subject.length<200);}
 assert.match(cadenceHtml('<script>alert(1)</script>\nhttps://example.test/u'),/&lt;script&gt;/);
 assert.match(cadenceHtml('https://example.test/u'),/<a href=/);
 assert.equal(companyDomain('https://www.alfa.com.br/a'),'alfa.com.br');assert.equal(companyDomain('https://linkedin.com/company/a'),'');
 assert.equal(chooseCandidate([{name:'A',position:'CEO',hash:'h',emails:[]},{name:'B',position:'CEO',hash:'h2',emails:[]}],''),null);
 assert.equal(validateReply({kind:'hot',confidence:.6,summary:'Talvez'}).kind,'review');
 assert.throws(()=>validateReply({kind:'hot',confidence:NaN,summary:''}));
 assert.throws(()=>graphPagePath('https://evil.test/v1.0/users/a/messages','a'));
 assert.equal(replyToken(`Re: [Ciatos:${user}]`),user);
 assert.match(hotAlertText({lead:{empresa:'Alfa'},lead_id:user,organization_id:org,summary:'Pediu reunião'},'https://crm.test'),/Não informado/);
});
test('classificador prioriza descadastro e tolera IA desligada sem inventar lead quente',async()=>{
 let called=false;const request=async()=>{called=true;throw new Error('no network');};
 assert.equal((await classifyReply(()=>undefined,'Por favor, descadastrar meu e-mail',request)).kind,'opt_out');
 assert.equal((await classifyReply(()=>undefined,'Quero conversar',request)).kind,'review');assert.equal(called,false);
});
test('agente: biblioteca idempotente, Radar persistente, alertas isolados, abertura não aquece e e-mail incerto não repete',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,service_role;grant execute on function auth.uid() to authenticated,service_role;`);
 const migrations=readdirSync('supabase/migrations').sort();for(const f of migrations.slice(0,2))await db.exec(readFileSync(`supabase/migrations/${f}`,'utf8'));
 await db.exec(`insert into auth.users values('${user}'),('${other}');insert into crm.profiles(id,nome,email,papel) values('${user}','Ana','a@example.test','ADMIN'),('${other}','B','b@example.test','ADMIN');`);
 for(const f of migrations.slice(2))await db.exec(readFileSync(`supabase/migrations/${f}`,'utf8'));
 await db.exec(`insert into crm.organizations(id,nome,slug) values('${other}','Outra','outra');delete from crm.organization_members where user_id='${other}';insert into crm.organization_members(organization_id,user_id,papel) values('${other}','${other}','ADMIN');set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);`);
 const install=()=>db.query<{n:number}>(`select crm.install_sdr_library($1,$2::jsonb) n`,[org,JSON.stringify(cadenceLibrary)]);
 assert.equal((await install()).rows[0].n,10);assert.equal((await install()).rows[0].n,0);
 const sid=(await db.query<any>(`select id from crm.outreach_sequences where settings->>'library_key'='contabilidade'`)).rows[0].id;
 await db.exec(`select crm.set_cadence_state('${sid}','ACTIVE');select crm.save_sdr_settings('${org}',true,'${sid}',true,'Finalidade avaliada para público empresarial','diego.garcia@grupociatos.com.br',true);reset role;`);
 const worker=(await db.query<any>('select crm.claim_sdr_worker() token')).rows[0].token;assert.ok(worker);
 assert.equal((await db.query<any>('select crm.claim_sdr_worker() token')).rows[0].token,null);
 await db.query(`select crm.finish_sdr_worker($1,'{"inbox":"idle"}')`,[worker]);
 await db.exec(`update crm.outreach_policy set sender='envio@example.test' where organization_id='${org}';`);
 const cursor=(await db.query<any>('select crm.claim_sdr_mailbox() c')).rows[0].c;assert.equal(cursor.mailbox,'envio@example.test');
 assert.equal((await db.query<any>('select crm.claim_sdr_mailbox() c')).rows[0].c,null);
 await db.query('select crm.finish_sdr_mailbox($1,$2,null,now(),null)',[cursor.mailbox,cursor.lease]);
 assert.equal((await db.query(`select * from crm.outreach_steps where tipo='NOTIFY_HUMAN'`)).rows.length,0);
 const mid=(await db.query<any>(`insert into crm.mining_jobs(organization_id,status,dados) values('${org}','Completed','{}') returning id`)).rows[0].id;
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);`);
 await db.query(`select crm.save_sdr_settings($1,true,$2,true,'Finalidade avaliada para público empresarial','diego.garcia@grupociatos.com.br',true,$3)`,[org,sid,mid]);
 assert.equal((await db.query<any>(`select radar_job_id from crm.sdr_settings where organization_id='${org}'`)).rows[0].radar_job_id,mid);
 await assert.rejects(db.query(`select crm.save_sdr_settings($1,true,$2,true,'Finalidade avaliada para público empresarial','diego.garcia@grupociatos.com.br',true,$3)`,[org,sid,other]));
 await db.exec('reset role;');
 await assert.rejects(db.query('delete from crm.mining_jobs where id=$1',[mid]));
 const excluded=(await db.query<any>(`insert into crm.mining_jobs(organization_id,status,dados) values('${org}','Completed','{}') returning id`)).rows[0].id;
 await db.query(`insert into crm.mining_leads(organization_id,job_id,cnpj_raw,dados) values($1,$2,'99999999000199',$3::jsonb)`,[org,excluded,JSON.stringify({tradeName:'Outra lista',emailCompany:'other@example.test'})]);
 await db.query(`insert into crm.mining_leads(organization_id,job_id,cnpj_raw,dados) values($1,$2,'12345678000190',$3::jsonb)`,[org,mid,JSON.stringify({tradeName:'Alfa',contactName:'Ana',emailCompany:'ana@alfa.test',phoneCompany:'31999999999',website:'alfa.test'})]);
 assert.equal((await db.query<any>('select crm.prepare_sdr_queue() n')).rows[0].n,1);assert.equal((await db.query<any>('select crm.prepare_sdr_queue() n')).rows[0].n,0);
 assert.equal((await db.query<any>(`select dados->>'radarJobId' job from crm.leads where organization_id='${org}'`)).rows[0].job,mid);
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${user}',false);`);
 const selected=(await db.query<any>(`select id from crm.leads where organization_id='${org}'`)).rows[0].id;
 const scoped=(await db.query<any>('select crm.enroll_radar_list($1,$2,$3,true) result',[sid,mid,[]])).rows[0].result;assert.equal(scoped.inscritos,0);
 await assert.rejects(db.query('select crm.enroll_radar_list($1,$2,$3,true)',[sid,other,[selected]]));
 await db.exec('reset role;');
 const q=(await db.query<any>('select crm.claim_sdr_lead() q')).rows[0].q;
 assert.equal(q.lead.empresa,'Alfa');assert.equal((await db.query<any>('select crm.claim_sdr_lead() q')).rows[0].q,null);
 await assert.rejects(db.query(`select crm.finish_sdr_lead($1,$2,'ENROLLED')`,[q.id,other]));
 await db.query(`select crm.finish_sdr_lead($1,$2,'ENROLLED')`,[q.id,q.lease]);
 const job=(await db.query<any>('select crm.claim_outreach() j')).rows[0].j;
 await db.exec(`update crm.sdr_mail_cursor set last_error='permission_missing';`);
 await db.exec(`update crm.sequence_enrollments set dry_run=false;`);
 const blocked=(await db.query<any>(`select crm.authorize_dispatch($1,$2) g`,[job.id,job.lease])).rows[0].g;
 assert.equal(blocked.allowed,false);assert.equal(blocked.reason,'reply_monitor_required');
 await db.exec(`update crm.sequence_enrollments set dry_run=false;update crm.automation_jobs set dispatch_started_at=now()-interval '1 minute',status='DONE' where id=${job.id};`);
 const pixel=(await db.query<any>(`select tracking_token from crm.automation_jobs where id=${job.id}`)).rows[0].tracking_token;
 await db.query(`select crm.record_sdr_open($1);`,[pixel]);await db.query(`select crm.record_sdr_open($1);`,[pixel]);
 assert.equal((await db.query(`select * from crm.message_events where event_type='email.opened'`)).rows.length,1);assert.equal((await db.query('select * from crm.sdr_alerts')).rows.length,0);
 await db.query(`select crm.record_sdr_reply($1,'event-1','hot','Solicitou uma conversa')`,[job.id]);await db.query(`select crm.record_sdr_reply($1,'event-1','hot','Solicitou uma conversa')`,[job.id]);
 assert.equal((await db.query('select * from crm.sdr_alerts')).rows.length,1);assert.equal((await db.query<any>('select status from crm.sequence_enrollments')).rows[0].status,'STOPPED');
 const alert=(await db.query<any>('select crm.claim_sdr_alert() a')).rows[0].a;assert.equal(alert.recipient,'diego.garcia@grupociatos.com.br');assert.equal(alert.lead.telefone,'31999999999');
 await db.query('select crm.finish_sdr_alert($1,$2,false)',[alert.id,alert.mail_lease]);assert.equal((await db.query<any>('select crm.claim_sdr_alert() a')).rows[0].a,null);
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${other}',false);`);
 assert.equal((await db.query('select * from crm.sdr_alerts')).rows.length,0);assert.equal((await db.query<any>(`select crm.sdr_notifications('${org}') n`)).rows[0].n.length,0);
 await assert.rejects(db.exec(`select crm.record_sdr_reply(${job.id},'evil','hot','evil')`));await assert.rejects(db.exec(`select crm.install_sdr_library('${org}','[]')`));
 await db.exec(`select set_config('request.jwt.claim.sub','${user}',false)`);assert.equal((await db.query<any>(`select crm.sdr_notifications('${org}') n`)).rows[0].n[0].read,false);
 await db.query('select crm.read_sdr_notification($1)',[alert.id]);assert.equal((await db.query<any>(`select crm.sdr_notifications('${org}') n`)).rows[0].n[0].read,true);
 }finally{await db.close();}
});
