import React,{useCallback,useEffect,useRef,useState} from 'react';
import {supabase,initialPasswordRecovery} from '../lib/supabase';
import DefinirSenha from './DefinirSenha';
import {useDialog} from '../lib/useDialog';
export interface Company {id:string;nome:string;registration:Record<string,string>;operating_role:string;can_manage:boolean;can_platform?:boolean;is_master?:boolean;}
export interface WorkspaceProps {company?:Company;companies?:Company[];onCompanyChange?:(id:string)=>void;onCompaniesRefresh?:(id?:string)=>Promise<void>;}
export function CompanyShell({children}:{children:(props:WorkspaceProps)=>React.ReactNode}){
 const [uid,setUid]=useState<string|null>(null),[ready,setReady]=useState(false),[loading,setLoading]=useState(false),[companies,setCompanies]=useState<Company[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState('');
 const [recovery,setRecovery]=useState(initialPasswordRecovery);
 const generation=useRef(0);
 useEffect(()=>{let active=true;const apply=(id:string|null)=>{if(active){setUid(id);setReady(true);}};supabase.auth.getSession().then(({data})=>apply(data.session?.user.id||null));const {data}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')setRecovery(true);if(event==='SIGNED_OUT')setRecovery(false);apply(session?.user.id||null);});return()=>{active=false;generation.current++;data.subscription.unsubscribe();};},[]);
 const refresh=useCallback(async(preferred?:string)=>{
  if(!uid)return;const version=++generation.current;setLoading(true);setError('');
  try{const {data,error}=await supabase.rpc('my_companies');if(error)throw error;if(version!==generation.current)return;
   const list=(data||[]) as Company[];if(preferred&&list.some(c=>c.id===preferred))localStorage.setItem("crm-company:"+uid,preferred);setCompanies(list);setSelected(old=>{const wanted=preferred||old||localStorage.getItem('crm-company:'+uid);return list.some(c=>c.id===wanted)?wanted!:list[0]?.id||'';});
  }catch{if(version===generation.current){setCompanies([]);setError('Não foi possível carregar suas empresas. Tente novamente.');}}finally{if(version===generation.current)setLoading(false);}
 },[uid]);
 useEffect(()=>{generation.current++;setCompanies([]);setSelected('');if(uid)void refresh();return()=>{generation.current++;};},[uid,refresh]);
 const change=(id:string)=>{if(id===selected||!companies.some(c=>c.id===id))return;if(!window.confirm('Trocar de empresa? Salve o que estiver editando antes de continuar. Clientes e atividades permanecem na empresa de origem.'))return;localStorage.setItem('crm-company:'+uid,id);setSelected(id);};
 if(!ready)return <div className="view-loading" role="status">Carregando acesso…</div>;
 if(!uid)return <>{children({})}</>;
 if(recovery)return <DefinirSenha onConcluido={()=>{setRecovery(false);window.history.replaceState(null,'',window.location.pathname+window.location.search);}}/>;
 if(loading)return <div className="view-loading" role="status">Carregando suas empresas…</div>;
 if(!companies.length)return <div className="p-8 max-w-xl mx-auto space-y-5"><h1 className="text-2xl">Seu acesso às empresas</h1><p role={error?'alert':undefined}>{error||'Seu usuário ainda não está vinculado a uma empresa ativa. Solicite o acesso ao administrador do grupo.'}</p><button className="btn-navy" onClick={()=>void refresh()}>Tentar novamente</button><button className="ux-secondary" onClick={()=>void supabase.auth.signOut()}>Sair</button></div>;
 const company=companies.find(c=>c.id===selected);if(!company)return <div role="status">Selecionando empresa…</div>;
 return <React.Fragment key={uid+':'+company.id}>{children({company,companies,onCompanyChange:change,onCompaniesRefresh:refresh})}</React.Fragment>;
}

const roles=[['ADMIN','Administrador'],['MANAGER','Gerente'],['SDR','SDR / Prospecção'],['CLOSER','Consultor'],['OPERATIONAL','Operacional'],['CS','Pós-venda'],['MARKETING','Marketing']];
export function CompanyManager({company,onClose,onRefresh}:{company:Company;onClose:()=>void;onRefresh:(id?:string)=>Promise<void>}){
 const [creating,setCreating]=useState(false),[name,setName]=useState(company.nome),[details,setDetails]=useState(company.registration||{}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[members,setMembers]=useState<any[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('SDR');
 const close=()=>{if(busy)return;const dirty=name!==(creating?"":company.nome)||JSON.stringify(details)!==JSON.stringify(creating?{}:company.registration||{});if(!dirty||window.confirm("Fechar sem salvar as alterações do cadastro da empresa?"))onClose();};
 const ref=useDialog(close);
 const load=async()=>{const {data,error}=await supabase.rpc('company_users',{org:company.id});if(error)setError('Não foi possível carregar a equipe.');else setMembers(data||[]);};
 useEffect(()=>{void load();},[company.id]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {data,error}=await supabase.rpc('save_company',{company_id:creating?null:company.id,company_name:name,details});if(error)throw error;await onRefresh(data);onClose();}catch(e:any){setError(e.message||'Não foi possível salvar a empresa.');}finally{setBusy(false);}};
 const access=async(memberEmail:string,memberRole:string,enabled=true)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const {error}=await supabase.rpc('set_company_member',{org:company.id,member_email:memberEmail,member_role:memberRole,enabled});if(error)throw error;setEmail('');setNotice(enabled?'Acesso salvo para esta empresa.':'Acesso removido somente desta empresa.');await load();}catch(e:any){setError(e.message||'Não foi possível alterar o acesso.');}finally{setBusy(false);}};
 return <div className="fixed inset-0 z-[3100] bg-slate-900/70 flex items-center justify-center p-4"><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Empresas do grupo" className="lead-dialog"><div className="lead-dialog-header"><div><p className="eyebrow">EMPRESAS DO GRUPO</p><h1>{creating?'Cadastrar empresa':company.nome}</h1><p>Cada empresa tem seus próprios clientes, agenda e operação.</p></div><button className="ux-close" disabled={busy} aria-label="Fechar empresas" onClick={close}>✕</button></div><div className="lead-dialog-body space-y-6">
 {error&&<p className="ux-error" role="alert">{error}</p>}{notice&&<p className="app-notice" role="status">{notice}</p>}
 {company.can_platform&&<button className="ux-secondary" disabled={busy} onClick={()=>{setCreating(!creating);setName(creating?company.nome:'');setDetails(creating?company.registration||{}:{});setError('');}}>{creating?'Voltar à empresa atual':'+ Cadastrar outra empresa'}</button>}
 <form id="company-registration" onSubmit={save} className="space-y-4"><div className="ux-fields"><label className="ux-field">Nome da empresa *<input required minLength={2} maxLength={120} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="Ex.: Ciatos Contabilidade"/></label>{[['legalName','Razão social'],['cnpj','CNPJ'],['email','E-mail da empresa'],['phone','Telefone']].map(([key,label])=><label className="ux-field" key={key}>{label}<input maxLength={key==='cnpj'?18:160} type={key==='email'?'email':'text'} value={details[key]||''} disabled={busy} onChange={e=>setDetails({...details,[key]:e.target.value})}/></label>)}</div><p className="ux-hint">{creating?'A nova empresa começa sem clientes. Você será seu primeiro administrador.':'Alterar o cadastro não transfere clientes nem muda os acessos.'}</p></form>
 {!creating&&<section className="space-y-4"><h2>Quem pode trabalhar nesta empresa</h2><p>Vincule um usuário já cadastrado no CRM. O perfil vale somente para esta empresa.</p><form onSubmit={e=>{e.preventDefault();void access(email,role);}} className="ux-fields"><label className="ux-field">E-mail do usuário<input type="email" required value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label><label className="ux-field">Perfil nesta empresa<select value={role} disabled={busy} onChange={e=>setRole(e.target.value)}>{roles.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="btn-navy" disabled={busy}>Salvar acesso</button></form><div className="space-y-3">{members.map(m=><div key={m.id} className="border rounded-xl p-3 flex flex-wrap gap-3 justify-between"><div><strong>{m.nome}</strong><p>{m.email} · {roles.find(r=>r[0]===m.papel)?.[1]}</p></div><button className="ux-secondary" disabled={busy} onClick={()=>{if(window.confirm('Remover o acesso deste usuário somente a esta empresa?'))void access(m.email,m.papel,false);}}>Remover acesso</button></div>)}</div></section>}
 </div><div className="lead-dialog-footer"><button className="ux-secondary" disabled={busy} onClick={close}>Fechar</button><button type="submit" form="company-registration" className="btn-navy" disabled={busy}>{busy?'Salvando…':creating?'Criar empresa e entrar':'Salvar cadastro da empresa'}</button></div></div></div>;
}
