import React,{useState} from 'react';
import {NavigationState} from '../types';
const guides=[
 {id:'cadastro',title:'1. Cadastre o lead',description:'Clique em Novo Lead no menu. Preencha a empresa e avance para o contato. Os complementos são opcionais.',image:'lead-empresa.png',alt:'Cadastro de lead com etapas Empresa, Contato e Complementos, botão Fechar no topo e Cancelar no rodapé.'},
 {id:'contato',title:'2. Salve o contato',description:'Informe nome e telefone; adicione o e-mail se tiver. Clique em Salvar lead. Se ocorrer um erro, os campos são preservados para você corrigir e tentar novamente.',image:'lead-contato.png',alt:'Etapa Contato com campos de nome, telefone, e-mail e cargo, e botão Salvar lead.'},
 {id:'qualificacao',title:'3. Revise e qualifique',description:'O cadastro aparece na Fila de Qualificação. Confira a empresa e o contato, clique em Abrir cadastro para revisar e em Aprovar para pipeline para encaminhar ao comercial.',image:'qualificacao.png',alt:'Fila de Qualificação com uma empresa fictícia e ações para revisar e aprovar.'},
];
export default function HelpCenter({onNavigate,onCreate}:{onNavigate:(view:NavigationState['view'])=>void;onCreate:()=>void}){
 const [topic,setTopic]=useState('primeiros');
 return <section className="help-center"><div className="page-heading"><div><p className="eyebrow">AJUDA DO SEU WORKSPACE</p><h1>Um passo de cada vez.</h1><p>Aprenda a cadastrar, acompanhar e dar continuidade aos seus relacionamentos.</p></div></div><nav className="help-topics" aria-label="Tópicos de ajuda">{[['primeiros','Primeiros passos'],['rotina','Minha rotina'],['duvidas','Dúvidas frequentes']].map(([id,label])=><button key={id} aria-pressed={topic===id} onClick={()=>setTopic(id)}>{label}</button>)}</nav>
 {topic==='primeiros'&&<><div className="ux-next">As imagens abaixo usam dados fictícios. Nenhum cliente real foi usado neste guia.</div><div className="guide-list">{guides.map(g=><article className="surface" key={g.id}><h2>{g.title}</h2><p>{g.description}</p><details><summary>Ver imagem do passo a passo</summary><a href={'/help/'+g.image} target="_blank" rel="noreferrer" aria-label={'Ampliar imagem: '+g.title}><img src={'/help/'+g.image} alt={g.alt} loading="lazy"/></a><small>Clique na imagem para ampliar em outra aba.</small></details></article>)}</div><div className="surface"><h2>4. Acompanhe a próxima ação</h2><p>No Pipeline Comercial, clique no nome do lead para ver o histórico e registrar atividades. Para avançar, escolha Mover para etapa no cartão. Use Minha Agenda para organizar os retornos. Na Central da IA, revise cadências e itens em Precisa de você.</p><p>O modo atual de cadências é simulação. Cadastrar ou qualificar um lead não dispara mensagens.</p></div><div className="help-actions"><button className="btn-navy" onClick={onCreate}>Cadastrar meu próximo lead</button><button className="ux-secondary" onClick={()=>onNavigate('qualification')}>Abrir fila de qualificação</button></div></>}
 {topic==='rotina'&&<div className="guide-list">{[['Quem prospecta e qualifica','Cadastre o contato, revise a fila e encaminhe os leads qualificados.','qualification'],['Quem conduz as conversas','Acompanhe o pipeline, consulte o histórico do lead e registre a próxima atividade.','kanban'],['Quem cuida dos clientes','Consulte Clientes Ativos e acompanhe o relacionamento após o fechamento.','customers'],['Quem administra a operação','Revise as intervenções na Central da IA e organize as configurações e os acessos da equipe.','ai_center']].map(([title,text,view])=><article className="surface" key={view}><h2>{title}</h2><p>{text}</p><button className="text-action" onClick={()=>onNavigate(view as NavigationState['view'])}>Abrir esta área →</button></article>)}<p className="ux-hint">As permissões da sua conta continuam valendo. Se uma ação estiver indisponível, procure o administrador.</p></div>}
 {topic==='duvidas'&&<div className="surface help-faq">{[['Como sair de um cadastro?','Use Fechar (×) no topo, Cancelar no rodapé ou a tecla Esc. Se você já preencheu algo, confirme Sair sem salvar ou escolha Continuar cadastro.'],['Preciso preencher tudo?','Não. Empresa e contato são o essencial. A etapa Complementos é opcional e as informações podem ser atualizadas no dossiê depois.'],['O cadastro deu erro. Perdi os dados?','Não. O formulário permanece aberto. Leia a mensagem, corrija os campos necessários e tente salvar novamente. Se o CNPJ já existe, cancele e localize a empresa na busca do topo.'],['Como encontrar uma empresa?','Use a busca no topo por nome, empresa, e-mail ou CNPJ. Selecione o resultado para abrir o dossiê.'],['Qual a diferença entre lead e cliente?','Lead é um relacionamento em prospecção. A tela Clientes Ativos reúne os negócios marcados como ganhos. A base de múltiplos contratos por cliente ainda está em desenvolvimento.'],['A IA já envia mensagens sozinha?','Não nesta configuração. A Central informa o modo seguro. E-mail, WhatsApp e o SDR conversacional dependem da implantação e configuração das integrações.'],['Por que não vejo o mesmo menu de outra pessoa?','As áreas variam conforme o papel da conta. A ajuda orienta a rotina, mas não libera novos acessos.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
 </section>;
}
