import React,{useRef,useState} from 'react';
import {OnboardingTemplate,OnboardingTemplatePhase} from '../types';
import {useDialog} from '../lib/useDialog';
import './OnboardingTemplateEditor.css';
export default function OnboardingTemplateEditor({initial,serviceTypes,onSave,onClose}:{initial:Partial<OnboardingTemplate>;serviceTypes:string[];onSave:(value:OnboardingTemplate)=>Promise<void>;onClose:()=>void}){
 const [model,setModel]=useState(()=>({...initial,phases:[...(initial.phases||[])].sort((a,b)=>a.order-b.order).map(p=>({...p}))}));
 const original=useRef(JSON.stringify(model));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [active,setActive]=useState(model.phases[0]?.id||'');
 const dirty=original.current!==JSON.stringify(model);const close=()=>{if(!busy&&(!dirty||window.confirm('Descartar as alterações não salvas do modelo?')))onClose();};const dialog=useDialog(close);
 const update=(id:string,patch:Partial<OnboardingTemplatePhase>)=>setModel(m=>({...m,phases:m.phases.map(p=>p.id===id?{...p,...patch}:p)}));
 const move=(index:number,delta:number)=>setModel(m=>{const phases=[...m.phases];[phases[index],phases[index+delta]]=[phases[index+delta],phases[index]];return {...m,phases};});
 const add=()=>{const id=crypto.randomUUID();setModel(m=>({...m,phases:[...m.phases,{id,name:'',description:'',order:m.phases.length,defaultDueDays:1,mandatory:true,executor:'equipe'}]}));setActive(id);};
 const remove=(id:string)=>{if(!window.confirm('Remover esta fase do modelo? A remoção só será aplicada ao salvar.'))return;setModel(m=>({...m,phases:m.phases.filter(p=>p.id!==id)}));if(active===id)setActive(model.phases.find(p=>p.id!==id)?.id||'');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError('');if(!model.name?.trim()||!model.serviceType||!model.phases.length){setError('Informe o nome, o serviço e pelo menos uma fase.');return;}const invalid=model.phases.find(p=>!p.name.trim()||!Number.isInteger(p.defaultDueDays)||p.defaultDueDays<0);if(invalid){setActive(invalid.id);setError('Cada fase precisa de um nome e um prazo inteiro igual ou maior que zero.');return;}setBusy(true);try{await onSave({...model,id:model.id||crypto.randomUUID(),name:model.name.trim(),phases:model.phases.map((p,order)=>({...p,name:p.name.trim(),order}))} as OnboardingTemplate);}catch(e:any){setError(e?.message||'Não foi possível salvar. Suas alterações continuam aqui.');}finally{setBusy(false);}};
 return <div className="ote-backdrop"><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="ote-title" className="ote-dialog"><header className="ote-header"><div><p>JORNADAS DO CLIENTE</p><h2 id="ote-title">Organize seu modelo de onboarding</h2><span>Defina a sequência, os prazos e o que precisa ser entregue em cada etapa.</span></div><button type="button" disabled={busy} onClick={close} aria-label="Fechar editor">✕</button></header>
 <form onSubmit={save} className="ote-form"><div className="ote-body">{error&&<div className="ote-error" role="alert">{error}</div>}<fieldset disabled={busy} className="ote-basics"><legend>Sobre a jornada</legend><label>Nome do modelo<input required value={model.name||''} onChange={e=>setModel({...model,name:e.target.value})} placeholder="Ex.: Entrada de novos clientes da Contabilidade"/></label><label>Serviço<select required value={model.serviceType||''} onChange={e=>setModel({...model,serviceType:e.target.value})}><option value="">Selecione</option>{Array.from(new Set([...serviceTypes,...(model.serviceType?[model.serviceType]:[])])).map(s=><option key={s}>{s}</option>)}</select></label><label className="ote-wide">Objetivo da jornada<textarea rows={2} value={model.description||''} onChange={e=>setModel({...model,description:e.target.value})} placeholder="Qual resultado a equipe deve alcançar ao concluir esta jornada?"/></label></fieldset>
 <div className="ote-phases-heading"><div><h3>Etapas da implantação <span>{model.phases.length}</span></h3><p>Abra uma fase para editar. Use as setas para ajustar a ordem.</p></div><button type="button" disabled={busy} className="ote-secondary" onClick={add}>+ Adicionar fase</button></div>
 {!model.phases.length&&<div className="ote-empty"><h3>Comece pela primeira entrega</h3><p>Adicione uma fase, descreva o que deve ser feito e defina o prazo.</p><button type="button" disabled={busy} className="ote-primary" onClick={add}>Criar primeira fase</button></div>}
 <ol className="ote-phases">{model.phases.map((phase,index)=><li key={phase.id} className={active===phase.id?'ote-phase is-open':'ote-phase'}><div className="ote-phase-heading"><button type="button" className="ote-phase-toggle" disabled={busy} aria-expanded={active===phase.id} aria-controls={'phase-'+phase.id} onClick={()=>setActive(active===phase.id?'':phase.id)}><span className="ote-number">{index+1}</span><span><strong>{phase.name||'Dê um nome a esta fase'}</strong><small>{phase.executor==='cliente'?'Cliente':'Equipe'} · {phase.defaultDueDays} dia(s) após {index?'a fase anterior':'o início'} · {phase.mandatory?'Obrigatória':'Opcional'}</small></span><span aria-hidden="true">{active===phase.id?'−':'+'}</span></button><div className="ote-phase-tools"><button type="button" disabled={busy||index===0} aria-label={'Subir fase '+(index+1)} onClick={()=>move(index,-1)}>↑</button><button type="button" disabled={busy||index===model.phases.length-1} aria-label={'Descer fase '+(index+1)} onClick={()=>move(index,1)}>↓</button><button type="button" disabled={busy} className="ote-remove" aria-label={'Remover fase '+(index+1)} onClick={()=>remove(phase.id)}>Remover</button></div></div>
 {active===phase.id&&<fieldset id={'phase-'+phase.id} disabled={busy} className="ote-phase-fields"><legend className="sr-only">Editar fase {index+1}</legend><label className="ote-wide">Nome da fase<textarea aria-label="Nome da fase" rows={2} value={phase.name} onChange={e=>update(phase.id,{name:e.target.value})} placeholder="Ex.: Apresentação da equipe e alinhamento inicial"/></label><label className="ote-wide">Instruções para executar esta fase<textarea aria-label="Instruções para executar esta fase" rows={4} value={phase.description} onChange={e=>update(phase.id,{description:e.target.value})} placeholder="Descreva a entrega, os documentos necessários e como confirmar a conclusão."/></label><label>Prazo após {index?'a fase anterior':'o início'} (dias)<input type="number" min="0" step="1" value={Number.isFinite(phase.defaultDueDays)?phase.defaultDueDays:''} onChange={e=>update(phase.id,{defaultDueDays:e.target.value===''?NaN:Number(e.target.value)})}/><small>Dias corridos; vencimentos no fim de semana vão para segunda-feira.</small></label><label>Quem executa<select aria-label="Quem executa" value={phase.executor||'equipe'} onChange={e=>update(phase.id,{executor:e.target.value as 'cliente'|'equipe'})}><option value="equipe">Equipe</option><option value="cliente">Cliente</option></select><small>Indica quem realiza a entrega desta etapa.</small></label><label className="ote-check ote-wide"><input type="checkbox" checked={phase.mandatory!==false} onChange={e=>update(phase.id,{mandatory:e.target.checked})}/><span>Fase obrigatória para liberar as próximas etapas</span></label></fieldset>}</li>)}</ol>
 <p className="ote-note">Este modelo será usado ao iniciar novas jornadas. Implantações já iniciadas mantêm suas fases.</p></div><footer className="ote-footer"><span>{dirty?'Alterações ainda não salvas':'Modelo pronto para revisão'}</span><div><button type="button" className="ote-secondary" disabled={busy} onClick={close}>Cancelar</button><button type="submit" className="ote-primary" disabled={busy}>{busy?'Salvando…':'Salvar modelo'}</button></div></footer></form></div></div>;
}
