import React,{useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {useDialog} from '../lib/useDialog';
interface Client {id:string;nome:string;registration:Record<string,string>;ativo:boolean;master_email:string|null;active_users:number;}
export function PlatformAdmin({onClose}:{onClose:()=>void}){
 const [clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState('');
 const ref=useDialog(onClose);
 useEffect(()=>{let active=true;supabase.rpc('platform_clients').then(({data,error})=>{if(!active)return;if(error)setError('Não foi possível carregar o painel. Este acesso é exclusivo do dono da plataforma.');else setClients(data||[]);setLoading(false);});return()=>{active=false;};},[]);
 const shown=clients.filter(c=>[c.nome,c.registration.legalName,c.registration.cnpj,c.master_email].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <div className="fixed inset-0 z-[3200] bg-slate-900/70 flex items-center justify-center p-4"><section ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Administração da plataforma" className="lead-dialog"><header className="lead-dialog-header"><div><p className="eyebrow">CIATOS CRM · DONO DA PLATAFORMA</p><h1>Empresas clientes</h1><p>Administre a carteira de empresas e confira os responsáveis por cada operação.</p></div><button className="ux-close" aria-label="Fechar administração" onClick={onClose}>✕</button></header><div className="lead-dialog-body space-y-6">
 {loading?<p role="status">Carregando empresas…</p>:error?<p role="alert" className="ux-error">{error}</p>:<><div className="grid grid-cols-2 gap-4"><div className="border rounded-xl p-4"><p>Empresas cadastradas</p><strong className="text-3xl">{clients.length}</strong></div><div className="border rounded-xl p-4"><p>Com usuário master</p><strong className="text-3xl">{clients.filter(c=>c.master_email).length}</strong></div></div><label className="ux-field">Buscar empresa, CNPJ ou master<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Digite para filtrar"/></label><p className="ux-hint">O master administra somente suas empresas. Este painel não concede acesso automático aos clientes e atividades de cada operação.</p><div className="space-y-3">{shown.map(c=><article key={c.id} className="border border-slate-200 rounded-xl p-5 space-y-2"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold">{c.nome}</h2><span>{c.ativo?'Ativa':'Inativa'}</span></div><p>{c.registration.legalName||'Razão social não informada'}</p><p>CNPJ: {c.registration.cnpj||'Não informado'}</p><p><strong>Master:</strong> {c.master_email||'Ainda não definido'}</p><p className="text-sm text-slate-500">{c.active_users} acesso(s) ativo(s)</p></article>)}{!shown.length&&<p>Nenhuma empresa encontrada.</p>}</div></>}
 </div><footer className="lead-dialog-footer"><button className="ux-secondary" onClick={onClose}>Fechar painel</button></footer></section></div>;
}
