import React,{useEffect,useState,useRef} from 'react';
import {supabase} from '../lib/supabase';
import {useDialog} from '../lib/useDialog';
import './PlatformAdmin.css';
type Row=Record<string,any>;
type Snapshot={clients:Row[];plans:Row[];invoices:Row[];tickets:Row[];audit:Row[];settings:Row};
const empty:Snapshot={clients:[],plans:[],invoices:[],tickets:[],audit:[],settings:{}};
const tabs=[['overview','Visão geral','◈'],['clients','Empresas clientes','▦'],['plans','Planos e limites','◇'],['finance','Financeiro','＄'],['users','Usuários e acessos','◎'],['support','Suporte','☏'],['audit','Histórico','≡'],['settings','Configurações','⚙']];
const states:Row={internal:'Uso interno',trial:'Em teste',active:'Ativo',inactive:'Indisponível',past_due:'Em atraso',suspended:'Suspenso',cancelled:'Cancelado',pending:'Em aberto',paid:'Pago',void:'Cancelado',open:'Aberto',in_progress:'Em atendimento',resolved:'Resolvido'};
const roles:Row={ADMIN:'Administrador',MANAGER:'Gerente',SDR:'SDR',CLOSER:'Consultor',OPERATIONAL:'Operacional',CS:'Pós-venda',MARKETING:'Marketing'};
const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((c||0)/100);
const date=(s:string)=>s?new Intl.DateTimeFormat('pt-BR').format(new Date(s.length===10?s+'T12:00:00':s)):'—';
const today=()=>new Date().toISOString().slice(0,10);
const call=async(action:string,payload:Row={})=>{const {data,error}=await supabase.rpc('platform_console',{action,payload});if(error)throw new Error(error.message);return data;};
const Tag=({status}:{status:string})=><span className={'pa-tag pa-tag-'+status}>{states[status]||status}</span>;
export function PlatformAdmin({onClose}:{onClose:()=>void}){
 const [data,setData]=useState<Snapshot>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false);
 const [editor,setEditor]=useState(''),[form,setForm]=useState<Row>({}),[original,setOriginal]=useState(''),[org,setOrg]=useState(''),[members,setMembers]=useState<Row[]>([]),[memberLoading,setMemberLoading]=useState(false);
 const [memberForm,setMemberForm]=useState({nome:'',email:'',papel:'SDR',master:false});
 const [selected,setSelected]=useState('');
 const memberRequest=useRef(0);
 const dirty=!!editor?JSON.stringify(form)!==original:tab==='users'&&!!(memberForm.nome||memberForm.email);
 const canLeave=()=>!dirty||window.confirm('Descartar as alterações ainda não salvas?');
 const close=()=>{if(!busy&&canLeave())onClose();};const ref=useDialog(close);
 const refresh=async()=>{const next=await call('snapshot');setData({...empty,...next});};
 useEffect(()=>{let active=true;call('snapshot').then(next=>{if(active)setData({...empty,...next});}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const loadMembers=async(id:string)=>{const version=++memberRequest.current;setMemberLoading(true);setMembers([]);try{const list=await call('members',{organization_id:id});if(version===memberRequest.current)setMembers(list);}catch(e:any){if(version===memberRequest.current)setError(e.message);}finally{if(version===memberRequest.current)setMemberLoading(false);}};
 const navigate=(next:string)=>{if(busy||!canLeave())return;setSelected('');setMemberForm({nome:'',email:'',papel:'SDR',master:false});setEditor('');setTab(next);setQuery('');setFilter('all');setError('');setNotice('');};
 const edit=(kind:string,value:Row)=>{if(busy||!canLeave())return;setEditor(kind);setForm(value);setOriginal(JSON.stringify(value));setError('');setNotice('');};
 const change=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
 const company=(id:string)=>data.clients.find(c=>c.id===id)?.nome||'Plataforma';
 const clientForm=(c?:Row)=>({id:c?.id||crypto.randomUUID(),name:c?.nome||'',legalName:c?.registration?.legalName||'',cnpj:c?.registration?.cnpj||'',email:c?.registration?.email||'',phone:c?.registration?.phone||'',brand_name:c?.branding?.display_name||'',color:c?.branding?.color||'#123039'});
 const accountForm=(c:Row)=>({organization_id:c.id,plan_id:c.account?.plan_id||'',status:c.account?.status||'internal',billing_cycle:c.account?.billing_cycle||'monthly',price_cents:c.account?.price_cents||0,trial_ends_on:c.account?.trial_ends_on||'',next_billing_on:c.account?.next_billing_on||'',billing_email:c.account?.billing_email||c.registration?.email||'',notes:c.account?.notes||'',onboarding:c.account?.onboarding||'pending'});
 const openUsers=(id:string)=>{if(busy||!canLeave())return;setEditor('');setTab('users');setOrg(id);setMemberForm({nome:'',email:'',papel:'SDR',master:false});setError('');setNotice('');void loadMembers(id);};
 const mutate=async(action:string,payload:Row,message:string)=>{setBusy(true);setError('');setNotice('');try{const result=await call(action,payload);try{await refresh();}catch{setError('Alteração salva, mas não foi possível atualizar a lista. Reabra o painel para recarregar.');}setNotice(message);return result;}catch(e:any){setError(e.message||'Não foi possível salvar. Tente novamente.');return null;}finally{setBusy(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;if(editor==='account'&&['suspended','cancelled'].includes(form.status)&&!window.confirm('Esta alteração bloqueará o acesso à empresa e pausará suas cadências. Confirmar?'))return;
 if(editor==='invoice'&&form.status==='paid'&&!window.confirm('Confirmar o registro manual de pagamento recebido? Nenhum valor será cobrado pelo sistema.'))return;
 const result=await mutate(editor+'_save',form,'Alterações salvas.');if(result){setEditor('');if(editor==='client'){setTab('clients');setQuery('');setNotice('Empresa salva. Agora defina o contrato e vincule um usuário master.');}if(editor==='plan')setTab('plans');if(editor==='account')setTab('clients');if(editor==='invoice')setTab('finance');if(editor==='ticket')setTab('support');}};
 const invite=async(e:React.FormEvent)=>{e.preventDefault();if(!org||busy)return;setBusy(true);setError('');setNotice('');try{
 const {data:result,error}=await supabase.functions.invoke('crm-admin-users',{body:{action:memberForm.master?'create-master':'create',organization_id:org,nome:memberForm.nome,email:memberForm.email,papel:memberForm.papel,departamento:'Comercial',redirectTo:window.location.origin}});
 if(error||result?.error)throw new Error(result?.error||'Não foi possível cadastrar o acesso. Confira os dados e tente novamente.');
 await loadMembers(org);await refresh();setMemberForm({nome:'',email:'',papel:'SDR',master:false});setNotice(result.contaExistente?'Usuário vinculado. A senha existente foi preservada.':result.emailEnviado?`Convite enviado para ${memberForm.email}. A pessoa cria a própria senha pelo link do e-mail.`:'Usuário criado, mas o e-mail não saiu. Copie o link exibido e envie para a pessoa.');if(!result.emailEnviado&&result.inviteLink)window.prompt('Link de acesso (envie para a pessoa):',result.inviteLink);
 }catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const updateMember=async(m:Row,patch:Row)=>{if(!window.confirm('Confirmar a alteração do acesso de '+m.email+' nesta empresa?'))return;const result=await mutate('member_save',{organization_id:org,user_id:m.id,role:m.role,is_master:m.is_master,active:m.active,...patch},'Acesso atualizado somente nesta empresa.');if(result)await loadMembers(org);};
 const exportClients=()=>{const rows=[['Empresa','CNPJ','Plano','Situação','Master','Usuários','Contatos'],...data.clients.map(c=>[c.nome,c.registration?.cnpj||'',c.plan_name||'Sem plano',states[c.account?.status]||'Uso interno',c.master_email||'',c.active_users,c.lead_count])];const escape=(v:any)=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(escape).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='empresas-crm.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const filtered=data.clients.filter(c=>[c.nome,c.registration?.legalName,c.registration?.cnpj,c.master_email].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||c.account?.status===filter));
 const mrr=data.clients.filter(c=>c.account?.status==='active').reduce((n,c)=>n+(c.account.billing_cycle==='annual'?c.account.price_cents/12:c.account.price_cents),0);
 const openValue=data.invoices.filter(i=>i.status==='pending').reduce((n,i)=>n+i.amount_cents,0);
 const received=data.invoices.filter(i=>i.status==='paid'&&i.paid_at?.slice(0,7)===today().slice(0,7)).reduce((n,i)=>n+i.amount_cents,0);
 const alerts=data.clients.filter(c=>!c.master_email||c.account?.status==='past_due'||c.account?.status==='trial'&&!c.available||c.account?.onboarding==='pending');
 const input=(key:string,label:string,type='text',required=false)=><label className="pa-field" key={key}>{label}<input type={type} required={required} disabled={busy} maxLength={type==='text'?500:undefined} value={form[key]??''} onChange={e=>change(key,e.target.value)}/></label>;
 const amount=(key:string,label:string)=><label className="pa-field">{label}<input type="number" min="0" max="10000000" step="0.01" required disabled={busy} value={(form[key]??0)/100} onChange={e=>change(key,Math.round(Number(e.target.value)*100))}/></label>;
 const select=(key:string,label:string,options:Row)=><label className="pa-field">{label}<select aria-label={label} disabled={busy} value={form[key]??''} onChange={e=>change(key,e.target.value)}>{Object.entries(options).map(([v,l])=><option key={v} value={v}>{String(l)}</option>)}</select></label>;
 const area=(key:string,label:string)=><label className="pa-field pa-wide">{label}<textarea disabled={busy} rows={3} maxLength={4000} value={form[key]||''} onChange={e=>change(key,e.target.value)}/></label>;
 const current=data.clients.find(c=>c.id===selected);
 const companySection=(section:string)=>{if(busy||!canLeave()||!current)return;setEditor('');setError('');setNotice('');setMemberForm({nome:'',email:'',papel:'SDR',master:false});if(section==='client'||section==='account'){const value=section==='client'?clientForm(current):accountForm(current);setEditor(section);setForm(value);setOriginal(JSON.stringify(value));}else if(section==='users'){setTab('users');setOrg(current.id);void loadMembers(current.id);}else setTab('finance');};
 const clientOptions=Object.fromEntries(data.clients.map(c=>[c.id,c.nome]));
 const editorTitles:Row={client:'Cadastro da empresa',plan:'Plano comercial',account:'Contrato e assinatura',invoice:'Registro financeiro',ticket:'Atendimento',settings:'Configurações da plataforma'};
 return <div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Administração da plataforma" className="platform-console">
 <aside className="pa-sidebar"><div className="pa-brand"><span>ciatos.</span><small>ADMINISTRAÇÃO DA PLATAFORMA</small></div><nav aria-label="Áreas da administração">{tabs.map(([id,label,icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>navigate(id)} disabled={busy}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="pa-side-note">Seu negócio, sob controle.<small>Acesso exclusivo do proprietário.</small></div><button className="pa-back" disabled={busy} onClick={close}>← Minha empresa</button></aside>
 <section className="pa-workspace"><header className="pa-header"><div><p>ADMINISTRAR O CRM · ESPAÇO DO PROPRIETÁRIO</p><h1>{editor?editorTitles[editor]:tabs.find(t=>t[0]===tab)?.[1]}</h1></div><button className="ux-close" aria-label="Fechar administração" disabled={busy} onClick={close}>✕</button></header>
 <main className="pa-content">{current&&<section className="pa-company-context"><button className="pa-breadcrumb" disabled={busy} onClick={()=>navigate('clients')}>← Todas as empresas</button><div className="pa-context-title"><h2>{current.nome}</h2><Tag status={current.account?.status||'internal'}/></div><p>{current.registration?.cnpj||'CNPJ não informado'} · {current.master_email||'Master ainda não definido'}</p><nav aria-label="Gestão desta empresa">{[['client','Cadastro'],['account','Contrato'],['users','Usuários'],['finance','Financeiro da empresa']].map(([id,label])=><button key={id} aria-current={(editor===id||!editor&&tab===id)?'page':undefined} disabled={busy} onClick={()=>companySection(id)}>{label}</button>)}</nav></section>}{error&&<div className="pa-message pa-error" role="alert">{error}{!loading&&!data.clients.length&&<button onClick={()=>{setError('');void refresh().catch(e=>setError(e.message));}}>Tentar novamente</button>}</div>}{notice&&<div className="pa-message" role="status">{notice}</div>}
 {loading?<div className="pa-empty" role="status">Carregando a administração…</div>:editor?<form onSubmit={save} className="pa-card pa-editor"><div className="pa-editor-intro"><h2>{editorTitles[editor]}</h2><p>{editor==='account'?company(form.organization_id):'Os dados são salvos somente ao confirmar este formulário.'}</p></div><div className="pa-form-grid">
 {editor==='client'&&<>{input('name','Nome da empresa *','text',true)}{input('legalName','Razão social')}{input('cnpj','CNPJ')}{input('email','E-mail da empresa','email')}{input('phone','Telefone')}{input('brand_name','Nome exibido na operação')}{input('color','Cor da empresa','color')}<p className="pa-hint">A nova empresa começa sem contatos e sem envios. Depois de salvar, defina seu master em Usuários e acessos.</p></>}
 {editor==='plan'&&<>{input('name','Nome do plano *','text',true)}{select('active','Disponível para novas assinaturas',{'true':'Sim','false':'Não'})}{amount('monthly_cents','Preço mensal (R$)')}{amount('annual_cents','Preço anual (R$)')}{input('max_users','Limite de usuários ativos','number')}{input('max_leads','Limite de contatos','number')}{area('description','Descrição do plano')}<p className="pa-hint pa-wide">Limite vazio significa ilimitado. Alterar o preço do catálogo não muda contratos já negociados. Não é permitido reduzir limites abaixo do uso atual.</p></>}
 {editor==='account'&&<>{select('plan_id','Plano',{'':'Sem plano / uso interno',...Object.fromEntries(data.plans.filter(p=>p.active||p.id===form.plan_id).map(p=>[p.id,p.name]))})}{select('status','Situação da assinatura',{internal:'Uso interno',trial:'Em teste',active:'Ativo',past_due:'Em atraso (acesso mantido)',suspended:'Suspenso',cancelled:'Cancelado'})}{select('billing_cycle','Periodicidade',{monthly:'Mensal',annual:'Anual'})}{amount('price_cents','Valor contratado por período (R$)')}{input('trial_ends_on','Fim do período de teste','date',form.status==='trial')}{input('next_billing_on','Próximo vencimento','date')}{input('billing_email','E-mail financeiro','email')}{select('onboarding','Configuração inicial',{pending:'Pendente',ready:'Concluída'})}{area('notes','Observações do contrato')}<p className="pa-hint pa-wide">Suspender ou cancelar bloqueia a operação e pausa cadências. Reativar não retoma disparos automaticamente. “Em atraso” mantém o acesso para negociação. O valor é um registro contratual; não gera cobrança automática.</p></>}
 {editor==='invoice'&&<>{select('organization_id','Empresa',clientOptions)}{input('reference','Referência *','text',true)}{input('description','Descrição *','text',true)}{amount('amount_cents','Valor (R$)')}{input('due_on','Vencimento *','date',true)}{select('status','Situação do registro',{pending:'Em aberto',paid:'Pago (registro manual)',void:'Cancelado'})}{area('notes','Observações / justificativa')}<p className="pa-hint pa-wide">Controle interno: não emite boleto, nota fiscal, Pix nem movimenta dinheiro. Um pagamento registrado só pode ser cancelado com justificativa.</p></>}
 {editor==='ticket'&&<>{select('organization_id','Empresa relacionada',{'':'Plataforma',...clientOptions})}{input('subject','Assunto *','text',true)}{select('priority','Prioridade',{low:'Baixa',normal:'Normal',high:'Alta'})}{select('status','Andamento',{open:'Aberto',in_progress:'Em atendimento',resolved:'Resolvido'})}{area('body','Descrição do atendimento')}{area('resolution','Resolução / encaminhamento')}</>}
 {editor==='settings'&&<>{input('product_name','Nome do produto *','text',true)}{input('support_email','E-mail de suporte','email')}{input('terms_url','Link dos termos de uso','url')}{input('privacy_url','Link da política de privacidade','url')}{area('commercial_notes','Orientações comerciais internas')}<p className="pa-hint pa-wide">Use esta área para informações comerciais. Credenciais de serviços são configuradas no servidor.</p></>}
 </div><div className="pa-form-actions"><button type="button" className="ux-secondary" disabled={busy} onClick={()=>{if(canLeave())setEditor('');}}>Cancelar</button><button className="btn-navy" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></form>:<>
 {tab==='overview'&&<><div className="pa-hero"><div><p>PRONTO PARA CRESCER COM VOCÊ</p><h2>{data.settings.product_name||'Ciatos CRM'}</h2><p>Acompanhe sua carteira, organize contratos e cuide de cada empresa.</p><button onClick={()=>edit('client',clientForm())}>+ Cadastrar empresa cliente</button></div><div className="pa-hero-stat"><strong>{data.clients.length}</strong><span>empresas na plataforma</span></div></div><div className="pa-metrics"><Metric label="Receita mensal contratada" value={money(mrr)} hint="Contratos ativos; anual dividido por 12"/><Metric label="Recebido neste mês" value={money(received)} hint="Pagamentos registrados manualmente"/><Metric label="Valores em aberto" value={money(openValue)} hint="Registros financeiros não liquidados"/><Metric label="Atendimentos abertos" value={data.tickets.filter(t=>t.status!=='resolved').length} hint="Acompanhe na área de suporte"/></div><div className="pa-two"><section className="pa-card"><h2>Precisa da sua atenção</h2>{!alerts.length?<p className="pa-empty">Nenhuma pendência de cadastro ou contrato.</p>:alerts.slice(0,8).map(c=><button key={c.id} className="pa-alert-row" onClick={()=>!c.master_email?openUsers(c.id):edit('account',accountForm(c))}><strong>{c.nome}</strong><span>{!c.master_email?'Definir master':c.account?.status==='past_due'?'Contrato em atraso':!c.available?'Acesso indisponível':'Concluir configuração'} →</span></button>)}</section><section className="pa-card"><h2>Preparação para vender</h2><div className="pa-steps">{[['plans','Definir planos e preços',data.plans.some(p=>p.active)],['clients','Cadastrar empresas clientes',data.clients.length>0],['users','Vincular responsáveis master',data.clients.length>0&&data.clients.every(c=>c.master_email)],['settings','Definir suporte e documentos',!!(data.settings.support_email&&data.settings.terms_url&&data.settings.privacy_url)]].map(([target,label,done],index)=><button key={String(target)} onClick={()=>navigate(String(target))}><span>{done?'✓':index+1}</span><strong>{label}</strong><small>{done?'Revisar':'Configurar'} →</small></button>)}</div><p className="pa-hint">O painel gerencia sua operação comercial. Cobranças automáticas dependem da integração de um provedor.</p></section></div></>}
 {tab==='clients'&&selected&&<section className="pa-card"><h2>Empresa em foco</h2><p>Use as abas acima para consultar o cadastro, ajustar o contrato, administrar usuários ou acompanhar os registros financeiros desta empresa.</p></section>}
 {tab==='clients'&&!selected&&<><div className="pa-toolbar"><label className="pa-search">Buscar empresa, CNPJ ou master<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Digite para filtrar"/></label><label className="pa-field">Situação<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option>{['internal','trial','active','past_due','suspended','cancelled'].map(s=><option key={s} value={s}>{states[s]}</option>)}</select></label><button className="ux-secondary" onClick={exportClients}>Exportar CSV</button><button className="btn-navy" onClick={()=>edit('client',clientForm())}>+ Nova empresa</button></div><p className="pa-hint">{filtered.length} empresa(s). Cada operação mantém seus dados separados. O painel não abre a carteira comercial do cliente.</p><div className="pa-card pa-company-list"><div className="pa-list-head" aria-hidden="true"><span>Empresa / responsável</span><span>Plano e situação</span><span>Uso atual</span><span>Gestão</span></div>{filtered.map(c=><article key={c.id} className="pa-company-row"><div><h2>{c.nome}</h2><p>{c.registration?.cnpj||'CNPJ não informado'}</p><p className="pa-master">{c.master_email||'Master ainda não definido'}</p></div><div><Tag status={c.account?.status||'internal'}/><p>{c.plan_name||'Uso interno / sem plano'}</p>{!c.available&&<p className="pa-warning">Acesso indisponível</p>}</div><div><p>{c.active_users} / {c.max_users??'∞'} usuários</p><p>{c.lead_count||0} / {c.max_leads??'∞'} contatos</p></div><button className="btn-navy" aria-label={'Gerenciar '+c.nome} onClick={()=>{setSelected(c.id);edit('client',clientForm(c));}}>Gerenciar →</button></article>)}</div>{!filtered.length&&<div className="pa-empty">Nenhuma empresa encontrada.</div>}</>}
 {tab==='plans'&&<><div className="pa-toolbar"><p>Preços de catálogo e limites reais por empresa.</p><button className="btn-navy" onClick={()=>edit('plan',{id:crypto.randomUUID(),name:'',monthly_cents:0,annual_cents:0,max_users:'',max_leads:'',active:'true',description:''})}>+ Novo plano</button></div><div className="pa-client-grid">{data.plans.map(p=><article className="pa-card" key={p.id}><Tag status={p.active?'active':'inactive'}/><h2>{p.name}</h2><div className="pa-price">{money(p.monthly_cents)}<small>/ mês</small></div><p>{money(p.annual_cents)} por ano</p><p>{p.max_users??'Ilimitados'} usuários · {p.max_leads??'Ilimitados'} contatos</p><p>{p.description}</p><button className="ux-secondary" onClick={()=>edit('plan',{...p,active:String(p.active),max_users:p.max_users??'',max_leads:p.max_leads??''})}>Editar plano</button></article>)}</div>{!data.plans.length&&<div className="pa-empty"><h2>Seu catálogo começa aqui</h2><p>Defina os planos e preços que deseja oferecer. Nenhum valor foi definido automaticamente.</p></div>}</>}
 {tab==='finance'&&<>{!selected&&<div className="pa-metrics"><Metric label="Em aberto" value={money(openValue)} hint="Controle interno"/><Metric label="Recebido no mês" value={money(received)} hint="Baixas manuais"/><Metric label="Em atraso" value={money(data.invoices.filter(i=>i.status==='pending'&&i.due_on<today()).reduce((n,i)=>n+i.amount_cents,0))} hint="Vencimento anterior a hoje"/></div>}<div className="pa-toolbar"><p>Registre valores combinados e pagamentos recebidos.</p><button className="btn-navy" disabled={!data.clients.length} onClick={()=>edit('invoice',{id:crypto.randomUUID(),organization_id:selected||data.clients[0]?.id,reference:'',description:'',amount_cents:0,due_on:today(),status:'pending',notes:''})}>+ Novo registro</button></div><div className="pa-card pa-table-wrap"><table><thead><tr><th>Empresa / referência</th><th>Vencimento</th><th>Valor</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{data.invoices.filter(i=>!selected||i.organization_id===selected).map(i=><tr key={i.id}><td><strong>{company(i.organization_id)}</strong><small>{i.reference} · {i.description}</small></td><td>{date(i.due_on)}</td><td>{money(i.amount_cents)}</td><td><Tag status={i.status}/></td><td><button onClick={()=>edit('invoice',{...i,notes:i.notes||''})}>Abrir registro</button></td></tr>)}</tbody></table>{!data.invoices.some(i=>!selected||i.organization_id===selected)&&<p className="pa-empty">Nenhum registro financeiro. Não há cobrança automática habilitada.</p>}</div></>}
 {tab==='users'&&<><div className="pa-card"><h2>Um usuário, várias empresas</h2><p>Vincule o mesmo e-mail às empresas autorizadas, com um perfil próprio em cada operação.</p>{!selected&&<label className="pa-field">Empresa para administrar acessos<select value={org} disabled={busy||memberLoading} onChange={e=>{if(!canLeave())return;setOrg(e.target.value);setMemberForm({nome:'',email:'',papel:'SDR',master:false});setError('');setNotice('');void loadMembers(e.target.value);}}><option value="">Selecione uma empresa</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label>}</div>{org&&<><form className="pa-card" onSubmit={invite}><h2>Cadastrar ou vincular usuário</h2><div className="pa-form-grid"><label className="pa-field">Nome do usuário<input required disabled={busy} value={memberForm.nome} onChange={e=>setMemberForm({...memberForm,nome:e.target.value})}/></label><label className="pa-field">E-mail do usuário<input type="email" required disabled={busy} value={memberForm.email} onChange={e=>setMemberForm({...memberForm,email:e.target.value})}/></label><label className="pa-field">Perfil nesta empresa<select disabled={busy||memberForm.master} value={memberForm.papel} onChange={e=>setMemberForm({...memberForm,papel:e.target.value})}>{Object.entries(roles).map(([id,label])=><option key={id} value={id}>{String(label)}</option>)}</select></label><label className="pa-checkbox"><input type="checkbox" disabled={busy} checked={memberForm.master} onChange={e=>setMemberForm({...memberForm,master:e.target.checked})}/>Responsável master desta empresa</label></div><p className="pa-hint">Nova conta: a pessoa recebe um e-mail com link para criar a própria senha. Conta existente: senha preservada. Ser master não concede administração da plataforma.</p><button className="btn-navy" disabled={busy||memberLoading}>{busy?'Salvando…':'Salvar acesso'}</button></form><section className="pa-card"><h2>Equipe de {company(org)}</h2>{memberLoading?<p role="status">Carregando equipe…</p>:members.length?members.map(m=><div className="pa-member" key={m.id}><div><strong>{m.nome}</strong><p>{m.email}</p><small>{m.is_master?'Master':roles[m.role]} · {m.active?'Ativo':'Sem acesso'}{!m.profile_active?' · Identidade inativa':''}</small></div><div className="pa-actions"><select aria-label={'Perfil de '+m.nome} disabled={busy||m.is_master||!m.active} value={m.role} onChange={e=>void updateMember(m,{role:e.target.value})}>{Object.entries(roles).map(([id,label])=><option key={id} value={id}>{String(label)}</option>)}</select><button disabled={busy||!m.active} onClick={()=>void updateMember(m,{is_master:!m.is_master})}>{m.is_master?'Remover master':'Tornar master'}</button><button disabled={busy} onClick={()=>void updateMember(m,{active:!m.active})}>{m.active?'Suspender vínculo':'Reativar vínculo'}</button></div></div>):<p className="pa-empty">Nenhum usuário vinculado. Cadastre o master para concluir a configuração.</p>}</section></>}</>}
 {tab==='support'&&<><div className="pa-toolbar"><p>Registre e acompanhe os atendimentos aos clientes.</p><button className="btn-navy" onClick={()=>edit('ticket',{id:crypto.randomUUID(),organization_id:'',subject:'',body:'',priority:'normal',status:'open',resolution:''})}>+ Novo atendimento</button></div><div className="pa-client-grid">{data.tickets.map(t=><article key={t.id} className="pa-card"><Tag status={t.status}/><h2>{t.subject}</h2><p>{company(t.organization_id)} · {t.priority==='high'?'Alta prioridade':t.priority==='low'?'Baixa prioridade':'Prioridade normal'}</p><p className="pa-preserve">{t.body}</p>{t.resolution&&<p><strong>Resolução:</strong> {t.resolution}</p>}<small>Atualizado em {date(t.updated_at)}</small><div><button className="ux-secondary" onClick={()=>edit('ticket',{...t,organization_id:t.organization_id||''})}>Abrir atendimento</button></div></article>)}</div>{!data.tickets.length&&<p className="pa-empty">Nenhum atendimento registrado.</p>}</>}
 {tab==='audit'&&<section className="pa-card pa-table-wrap"><h2>Histórico administrativo</h2><p>Últimas 200 alterações deste painel. A auditoria operacional continua em cada empresa.</p><table><thead><tr><th>Quando</th><th>Responsável</th><th>Alteração</th><th>Detalhes</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{date(a.created_at)}<small>{new Date(a.created_at).toLocaleTimeString('pt-BR')}</small></td><td>{a.actor_email||'Administrador'}</td><td>{({client_save:'Cadastro de empresa',account_save:'Contrato',plan_save:'Plano',member_save:'Acesso de usuário',invoice_save:'Registro financeiro',ticket_save:'Atendimento',settings_save:'Configuração'} as Row)[a.action]||a.action}<small>{company(a.entity_id)==='Plataforma'?'':company(a.entity_id)}</small></td><td>{a.details?.status?states[a.details.status]||a.details.status:'Alteração registrada'}{a.details?.role?' · '+roles[a.details.role]:''}</td></tr>)}</tbody></table>{!data.audit.length&&<p className="pa-empty">As próximas alterações administrativas aparecerão aqui.</p>}</section>}
 {tab==='settings'&&<><section className="pa-card"><h2>{data.settings.product_name||'Ciatos CRM'}</h2><dl className="pa-definition"><dt>Suporte</dt><dd>{data.settings.support_email||'Não configurado'}</dd><dt>Termos de uso</dt><dd>{data.settings.terms_url||'Não configurado'}</dd><dt>Privacidade</dt><dd>{data.settings.privacy_url||'Não configurado'}</dd></dl><p className="pa-preserve">{data.settings.commercial_notes}</p><button className="btn-navy" onClick={()=>edit('settings',{...data.settings})}>Editar configurações</button></section><section className="pa-card"><h2>Integrações comerciais</h2><p>Gateway de pagamento, emissão fiscal, domínio próprio e envio de mensagens precisam de configuração e homologação antes da ativação.</p><p className="pa-hint">Este painel não altera credenciais nem habilita disparos. Os registros financeiros são controles internos.</p></section></>}
 </>}
 <footer className="pa-footer"><span>{data.settings.product_name||'Ciatos CRM'} · Administração da plataforma</span><button onClick={close} disabled={busy}>Fechar painel</button></footer></main></section></div>;
}
function Metric({label,value,hint}:{label:string;value:React.ReactNode;hint:string}){return <div className="pa-card pa-metric"><p>{label}</p><strong>{value}</strong><small>{hint}</small></div>;}
