/** Copy reviewed in the CRM before activation. No claims about a prospect's finances. */
export const cadenceLibrary = [
  { id: 'contabilidade', name: 'Contabilidade', question: 'Como a {{company}} acompanha hoje os prazos contábeis e as informações para decidir?', value: 'Nossa equipe de contabilidade pode conversar sobre a organização das rotinas, obrigações e informações de gestão.', topic: 'rotina contábil' },
  { id: 'juridico', name: 'Jurídico empresarial', question: 'Quem acompanha os contratos e as demandas jurídicas da {{company}}?', value: 'Podemos apresentar nosso atendimento jurídico empresarial e entender se existe uma demanda que mereça avaliação profissional.', topic: 'demandas jurídicas' },
  { id: 'crise', name: 'Planejamento de crise', question: 'Organizar prioridades e alternativas para os próximos meses é uma pauta da {{company}}?', value: 'Nosso trabalho de planejamento de crise começa entendendo o cenário e as prioridades da gestão, sem pressupor dificuldades nem prometer resultados.', topic: 'planejamento e prioridades' },
  { id: 'tributario', name: 'Planejamento tributário', question: 'A {{company}} tem uma revisão periódica do seu planejamento tributário?', value: 'Podemos conversar sobre uma avaliação técnica do enquadramento e das rotinas tributárias. Qualquer recomendação depende dos documentos e da análise da equipe.', topic: 'planejamento tributário' },
  { id: 'holding', name: 'Holding e planejamento patrimonial', question: 'Organização patrimonial e sucessão fazem parte dos planos dos sócios da {{company}}?', value: 'A equipe pode apresentar como funciona a avaliação de alternativas de organização patrimonial e sucessória. Uma holding só é considerada quando fizer sentido para o caso.', topic: 'organização patrimonial' },
  { id: 'credito', name: 'Recuperação de crédito tributário', question: 'A {{company}} já avaliou se existe documentação para uma revisão de créditos tributários?', value: 'Podemos explicar as etapas de uma revisão técnica. A existência de créditos, os valores e a viabilidade dependem de análise; não há resultado garantido.', topic: 'revisão de créditos tributários' },
  { id: 'bank', name: 'Ciatos Bank', question: 'Há alguma necessidade da {{company}} em serviços financeiros que você gostaria de conversar?', value: 'Podemos apresentar a Ciatos Bank e entender quais soluções disponíveis podem ser avaliadas pela equipe. Condições, custos e aprovação dependem da análise específica.', topic: 'serviços da Ciatos Bank' },
  { id: 'racionaliza', name: 'Racionaliza', question: 'Faz sentido conhecer a Racionaliza e avaliar se seus serviços atendem alguma necessidade da {{company}}?', value: 'Podemos organizar uma apresentação da Racionaliza com a equipe responsável, a partir das prioridades que você indicar.', topic: 'uma apresentação da Racionaliza' },
  { id: 'log', name: 'CiatosLog', question: 'Quem cuida das demandas de logística da {{company}}?', value: 'Podemos apresentar a CiatosLog e conversar sobre suas necessidades. Escopo, disponibilidade e condições são confirmados pela equipe.', topic: 'demandas de logística' },
  { id: 'cafeworking', name: 'Cafeworking', question: 'A equipe da {{company}} tem alguma demanda de espaço para trabalho ou reuniões?', value: 'Podemos apresentar o Cafeworking e verificar com a equipe as opções e a disponibilidade para sua necessidade.', topic: 'espaços para trabalho e reuniões' },
].map(s => ({
  ...s, publico: 'prospect', titulo: `${s.name} · apresentação e conversa`, espera_final: 5,
  passos: [
    { espera_dias: 0, assunto: `${s.name}: uma conversa com a {{company}}`, corpo: `Olá, {{name}}.\n\nSou o assistente comercial do Grupo Ciatos. ${s.question}\n\n${s.value}\n\nEsse assunto está com você ou há outra pessoa responsável? Se houver interesse, responda a este e-mail e organizamos o próximo contato.\n\nEquipe Grupo Ciatos` },
    { espera_dias: 3, assunto: `Sobre ${s.topic} na {{company}}`, corpo: `Olá, {{name}}.\n\nRetomo minha mensagem sobre ${s.topic}. ${s.value}\n\nQual é a principal prioridade da {{company}} nesse tema hoje? Uma resposta curta já ajuda a direcionar a conversa à pessoa certa.\n\nAssistente comercial · Grupo Ciatos` },
    { espera_dias: 4, assunto: `Podemos conversar sobre ${s.topic}?`, corpo: `Olá, {{name}}.\n\nSe ${s.topic} fizer sentido para a {{company}}, posso encaminhar seu interesse ao Diego Garcia para combinar uma conversa.\n\nVocê prefere informar um horário ou um telefone para retorno? Não é necessário enviar documentos ou dados financeiros por aqui.\n\nAssistente comercial · Grupo Ciatos` },
    { espera_dias: 5, assunto: `Encerrando este contato — {{company}}`, corpo: `Olá, {{name}}.\n\nComo não tivemos retorno, encerro esta sequência sobre ${s.topic}. Não vou continuar insistindo.\n\nSe o assunto ganhar prioridade depois, basta responder a este e-mail. Se preferir não receber outros contatos, use o link de descadastro abaixo.\n\nObrigado pelo seu tempo.\nAssistente comercial · Grupo Ciatos` },
  ],
}));
